server:
  port: 7200
  name: 权限管理

spring:
  main:
    banner-mode: off
  thymeleaf:
    cache: off
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    enabled: on
  profiles:
    active: dev
  security:
    user:
      name: ijunfu
      password: 123456