server:
  port: 7200
  name: 权限管理

spring:
  main:
    banner-mode: off
  thymeleaf:
    cache: off
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    enabled: on
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml